# Generated by Django 2.0 on 2021-01-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='留言序号')),
                ('message_text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='留言内容')),
                ('message_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='留言用户')),
                ('message_date', models.CharField(blank=True, max_length=150, null=True, verbose_name='日期')),
                ('message_like', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '网站留言',
                'verbose_name_plural': '网站留言',
            },
        ),
    ]
