# Generated by Django 2.0 on 2021-01-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerDynamic',
            fields=[
                ('dynamic_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('singer_plays', models.IntegerField(verbose_name='播放次数')),
                ('singer_search', models.IntegerField(verbose_name='搜索次数')),
                ('singer_down', models.IntegerField(verbose_name='下载次数')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singer.Singer', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '歌手动态',
                'verbose_name_plural': '歌手动态',
            },
        ),
    ]
