# Generated by Django 2.0 on 2021-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_singerdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_information',
            field=models.CharField(default='txt', max_length=45, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
