# Generated by Django 2.0 on 2021-01-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_singer_singer_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='singer_information',
            field=models.CharField(max_length=1000, verbose_name='简介'),
        ),
    ]
